### ISSUE TITLE
SoftUbiKey unable to config

### ISSUE THREAD

**Issue by TriMoon** [linuxmint/cinnamon-spices-applets#1779]
softyubikey@yubiserver.include.gr

```
 * Applet version/Build date Latest as of this writing
 * Cinnamon version: 3.6.7
 * Distribution - Debian 9.4 (Buster/sid)
 * Graphics hardware *and* driver used: NVidia GTX 1080 Ti (GP102), native nvidia driver

 ```

**Notify author of applet**
softyubikey@yubiserver.include.gr

**Issue**
Unable to configure applet.
When clicking the config menu item of the applet, nothing happens.
- No config icon in applets listing.

**Steps to reproduce**
Install and activate applet

**Comment by icarter09** [comment]
Cinnamon: 3.6.7
Linux Mint: 18.3
Applet version: 2017-10-02 00:59 UTC

Verified that this is issue is still occurring. Installed applet. Clicked on configure option, but nothing happens.

**Comment by jakub-vavra-cz** [comment]
Same issue on Fedora 33 Cinnamon spin
cinnamon-4.8.3-1.fc33.x86_64
Applet version:  2019-10-25 07:22:15

**Comment by patrakov** [comment]
This is due to the `.local/share/cinnamon/applets/softyubikey@yubiserver.include.gr/softyubikey-settings` script that became outdated. Here are the errors:

With python2:

```
.local/share/cinnamon/applets/softyubikey@yubiserver.include.gr/softyubikey-settings:4: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk as gtk
Traceback (most recent call last):
  File ".local/share/cinnamon/applets/softyubikey@yubiserver.include.gr/softyubikey-settings", line 75, in <module>
    confwin = CreateConfigWin()
  File ".local/share/cinnamon/applets/softyubikey@yubiserver.include.gr/softyubikey-settings", line 69, in __init__
    self.builder.add_from_file(os.path.expanduser('~/.local/share/cinnamon/applets/softyubikey@yubiserver.include.gr/ui/softyubikey.ui'))
gi.repository.GLib.Error: gtk-builder-error-quark: /home/aep/.local/share/cinnamon/applets/softyubikey@yubiserver.include.gr/ui/softyubikey.ui:22:41 Invalid property: GtkGrid.n_columns (11)
```

With python3:

```
Traceback (most recent call last):
  File "/home/aep/.local/share/cinnamon/applets/softyubikey@yubiserver.include.gr/softyubikey-settings", line 3, in <module>
    import sys,os,ConfigParser
```

Well, in python3, the module is called `configparser`, not `ConfigParser`. I have not tried to forward-port the script, and would suggest dropping the extension.
