### ISSUE TITLE
[hamster@projecthamster.wordpress.com]

### ISSUE THREAD

**Issue by groovenectar** [linuxmint/cinnamon-spices-applets#2003]
```
 * Applet version/Build date: Version 0.2
 * Project Hamster Version: 2.91.3
 * Cinnamon version: 3.8.9
 * Distribution: Mint 19
 * Graphics hardware *and* driver: nvidia-driver-390
 ```
Here is the error from `~/.xsession-errors` when I click "Show Overview"

```
(cinnamon:1783): Cjs-WARNING **: 16:57:48.955: JS ERROR: Exception in callback for signal: activate: Gio.IOErrorEnum: GDBus.Error:org.freedesktop.DBus.Python.GLib.Error: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/hamster-time-tracker/hamster-windows-service", line 38, in overview
  File "/usr/lib/python2.7/dist-packages/hamster/lib/configuration.py", line 149, in show
  File "/usr/lib/python2.7/dist-packages/hamster/overview.py", line 370, in __init__
    self.on_fact_selection_changed(self.fact_tree)
  File "/usr/lib/python2.7/dist-packages/hamster/overview.py", line 66, in __init__
    self.reports = TotalsBox()
  File "/usr/lib/python2.7/dist-packages/hamster/widgets/dates.py", line 42, in __init__
  File "/usr/lib/python2.7/dist-packages/hamster/lib/configuration.py", line 89, in load_ui_file
Error: g-file-error-quark: Failed to open file “/usr/share/hamster-time-tracker/date_range.ui”: No such file or directory (4)

_proxyInvoker@resource:///org/cinnamon/cjs/modules/overrides/Gio.js:94:16
_makeProxyMethod/<@resource:///org/cinnamon/cjs/modules/overrides/Gio.js:124:16
anonymous/HamsterApplet.prototype._onShowHamsterActivate@/home/dan/.local/share/cinnamon/applets/hamster@projecthamster.wordpress.com/applet.js:552:9
_emit@resource:///org/cinnamon/cjs/modules/signals.js:142:27
PopupBaseMenuItem.prototype.activate@/usr/share/cinnamon/js/ui/popupMenu.js:179:9
PopupBaseMenuItem.prototype._onButtonReleaseEvent@/usr/share/cinnamon/js/ui/popupMenu.js:152:9
```

```
$ cd /usr/share/hamster-applet/
$ ll
total 252
drwxr-xr-x   3 root root  4096 Oct  8 12:32 ./
drwxr-xr-x 370 root root 12288 Oct  8 12:32 ../
-rw-r--r--   1 root root 21110 Jun 25  2012 applet.ui
drwxr-xr-x   2 root root  4096 Oct  8 12:32 art/
-rw-r--r--   1 root root 17407 Jun 25  2012 edit_activity.ui
-rw-r--r--   1 root root   492 Jun 25  2012 Hamster_Applet.xml
-rw-r--r--   1 root root 19456 Jun 25  2012 hamster.db
-rw-r--r--   1 root root 31770 Jun 25  2012 hamster.ui
-rw-r--r--   1 root root 12646 Jun 25  2012 overview_totals.ui
-rw-r--r--   1 root root 19403 Jun 25  2012 overview.ui
-rw-r--r--   1 root root 48411 Jun 25  2012 preferences.ui
-rw-r--r--   1 root root 14850 Jun 25  2012 range_pick.ui
-rw-r--r--   1 root root 12632 Jun 25  2012 report_template.html
-rw-r--r--   1 root root 13786 Jun 25  2012 stats.ui
```
I had a hard time getting up and running with Hamster in the first place, on this platform. Am I using the wrong version of Hamster?

**Comment by jaszhix** [comment]
How did you install Hamster? As far as I'm aware Hamster is not being maintained anymore, and is no longer in the Ubuntu repos. May be worth considering removing the applet since I'm not sure how to reproduce this.

**Comment by groovenectar** [comment]
That seems to be the case unfortunately... Installed per the instructions here: https://github.com/projecthamster/hamster/issues/356#issuecomment-385915275

```
https://packages.ubuntu.com/artful/amd64/python-wnck/download
https://packages.ubuntu.com/artful/all/hamster-applet/download
```

Maybe I should try this one: https://github.com/projecthamster/hamster/issues/356#issuecomment-418404342

**Comment by groovenectar** [comment]
After the restart, Project Hamster wouldn't open at all. Probably going to through in the towel for the time being :( It's a shame to remove entirely since it's sooo close. Not sure of other options, since I'm sure we don't want broken stuff in the repo, but I wish I had more time to dig in the code right now. It seems like it's right on the verge of working fine with a few updates. Maybe in a few weeks!

**Comment by jaszhix** [comment]
Yeah, used to use Hamster a lot too. I use Waka Time now, it has integration with every editor you could think of, but its limited to coding.

**Comment by groovenectar** [comment]
Thanks for the tip! I'm going to give it a spin to check it out, even though it's doesn't exactly replace a project time tracker. If Waka Time had a self-hosted option, it would be super tight! Seems really cool. Still exploring various options. My goto has been https://www.kimai.org/

**Comment by FredericGuilbault** [comment]
The applet send the Dbus methods as expected 
The problem append on hamster-windows-service when Dbus try to launch it. 

The issue should be reported at https://github.com/projecthamster/hamster
