### ISSUE TITLE
SpicesUpdate@claudiux crashing Cinnamon

### ISSUE THREAD

**Issue by Gr3q** [linuxmint/cinnamon-spices-applets#2972]
```
 * Applet version/Build date (to be found in "About.." or in "metadata.json")
 * Cinnamon version 4.4.8
 * Distribution - Arch
 * AMD + amdgpu
 ```

**Notify author of applet**
@claudiux 

**Issue**
The Desklet cache was out of date, so I clicked on "Yes" on prompt "Do you want to Update it?". Cinnamon crashed.

This might not always happen I guess nor specific to Desklets, but I have no idea to be honest.

**Steps to reproduce**
1. There is a new Desklet update
2. Click on Desklets on Applet
3. Update Cache

**Expected behaviour**
Not crashing

**Other information**
Journalctl log with relevant stacktrace (same as before):
```
Apr 22 22:03:27 gr3q-desktop audit[2967]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=5 pid=2967 comm="cinnamon" exe="/usr/bin/cinnamon" sig=5 res=1
Apr 22 22:03:27 gr3q-desktop kernel: traps: cinnamon[2967] trap int3 ip:7f61804a6a36 sp:7ffc6b8b68e0 error:0 in libglib-2.0.so.0.6400.2[7f618045e000+8300>
Apr 22 22:03:27 gr3q-desktop kernel: audit: type=1701 audit(1587589407.418:319): auid=1000 uid=1000 gid=1000 ses=5 pid=2967 comm="cinnamon" exe="/usr/bin>
Apr 22 22:03:27 gr3q-desktop systemd[1]: Created slice system-systemd\x2dcoredump.slice.
Apr 22 22:03:27 gr3q-desktop audit: AUDIT1334 prog-id=46 op=LOAD
Apr 22 22:03:27 gr3q-desktop kernel: audit: type=1334 audit(1587589407.432:320): prog-id=46 op=LOAD
Apr 22 22:03:27 gr3q-desktop audit: AUDIT1334 prog-id=47 op=LOAD
Apr 22 22:03:27 gr3q-desktop systemd[1]: Started Process Core Dump (PID 11784/UID 0).
Apr 22 22:03:27 gr3q-desktop audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@0-11784-0 comm="systemd" exe=">
Apr 22 22:03:27 gr3q-desktop kernel: audit: type=1334 audit(1587589407.432:321): prog-id=47 op=LOAD
Apr 22 22:03:27 gr3q-desktop kernel: audit: type=1130 audit(1587589407.432:322): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@0->
Apr 22 22:03:28 gr3q-desktop systemd-coredump[11785]: Process 2967 (cinnamon) of user 1000 dumped core.
                                                      
                                                      Stack trace of thread 2967:
                                                      #0  0x00007f61804a6a36 n/a (libglib-2.0.so.0 + 0x64a36)
                                                      #1  0x00007f61804a3c37 g_log_default_handler (libglib-2.0.so.0 + 0x61c37)
                                                      #2  0x00007f61804a75ae g_logv (libglib-2.0.so.0 + 0x655ae)
                                                      #3  0x00007f61804a77b0 g_log (libglib-2.0.so.0 + 0x657b0)
                                                      #4  0x00007f6180193e6d n/a (libcjs.so.0 + 0x45e6d)
                                                      #5  0x00007f617d9f04af n/a (libmozjs-52.so + 0x4b54af)
                                                      #6  0x00007f617d9f1a82 n/a (libmozjs-52.so + 0x4b6a82)
                                                      #7  0x00007f617d9fccb8 n/a (libmozjs-52.so + 0x4c1cb8)
                                                      #8  0x00007f617d9fda9f n/a (libmozjs-52.so + 0x4c2a9f)
                                                      #9  0x00007f617d9fde5e n/a (libmozjs-52.so + 0x4c2e5e)
                                                      #10 0x00007f617d9fe13c n/a (libmozjs-52.so + 0x4c313c)
                                                      #11 0x00007f61801a1405 n/a (libcjs.so.0 + 0x53405)
                                                      #12 0x00007f61804ad58f g_main_context_dispatch (libglib-2.0.so.0 + 0x6b58f)
                                                      #13 0x00007f61804af531 n/a (libglib-2.0.so.0 + 0x6d531)
                                                      #14 0x00007f61804b0543 g_main_loop_run (libglib-2.0.so.0 + 0x6e543)
                                                      #15 0x00007f6180a910d3 meta_run (libmuffin.so.0 + 0x550d3)
                                                      #16 0x000055eb5de8a47e n/a (cinnamon + 0x247e)
                                                      #17 0x00007f618026e023 __libc_start_main (libc.so.6 + 0x27023)
                                                      #18 0x000055eb5de8a57e n/a (cinnamon + 0x257e)

```

**Comment by Gr3q** [comment]
Also happened when "Check regularly whether new applets are available" is turned off/on on the Applets page in settings.

If this is specific to Arch based distros I will post on Arch forum as well, but it would be nice to get a general idea what triggers the crash first.

**Comment by dragonhelios** [comment]
Having the same issue on Manjaro. 

@Gr3q any luck on figuring a solution?

**Comment by Gr3q** [comment]
@dragonhelios Not much, the issue is definitely in cjs, but I can't get the debug package work with cinnamon, so I'm not getting stacktraces where I really want to. Arch forum thread is [here](https://bbs.archlinux.org/viewtopic.php?id=254987) what I opened.

Stack trace:
```
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `cinnamon --replace --replace'.
Program terminated with signal SIGTRAP, Trace/breakpoint trap.
#0  _g_log_abort (breakpoint=1) at ../glib/glib/gmessages.c:554
554	    G_BREAKPOINT ();
[Current thread is 1 (Thread 0x7f201cd0ba00 (LWP 76738))]
(gdb) 
(gdb) bt
#0  _g_log_abort (breakpoint=1) at ../glib/glib/gmessages.c:554
#1  0x00007f2022b91c37 in g_log_default_handler
    (log_domain=log_domain@entry=0x7f20228bc079 "Cjs", log_level=log_level@entry=6, message=message@entry=0x55a624cfd2f0 "JS object wrapper for GObject 0x55a6261844b0 (GInotifyFileMonitor) is being released while toggle references are still pending.", unused_data=unused_data@entry=0x0)
    at ../glib/glib/gmessages.c:3123
#2  0x00007f2022b955ae in g_logv (log_domain=0x7f20228bc079 "Cjs", log_level=G_LOG_LEVEL_ERROR, format=<optimized out>, args=args@entry=0x7ffd553fdd20)
    at ../glib/glib/gmessages.c:1350
#3  0x00007f2022b957b0 in g_log (log_domain=<optimized out>, log_level=<optimized out>, format=<optimized out>) at ../glib/glib/gmessages.c:1415
#4  0x00007f2022881e6d in  () at /usr/lib/libcjs.so.0
#5  0x00007f20200f94af in  () at /usr/lib/libmozjs-52.so
#6  0x00007f20200faa82 in  () at /usr/lib/libmozjs-52.so
#7  0x00007f2020105cb8 in  () at /usr/lib/libmozjs-52.so
#8  0x00007f2020106a9f in  () at /usr/lib/libmozjs-52.so
#9  0x00007f2020106e5e in  () at /usr/lib/libmozjs-52.so
#10 0x00007f202010713c in  () at /usr/lib/libmozjs-52.so
#11 0x00007f202288f405 in  () at /usr/lib/libcjs.so.0
#12 0x00007f2022b9b58f in g_main_dispatch (context=0x55a6202ffad0) at ../glib/glib/gmain.c:3309
#13 g_main_context_dispatch (context=context@entry=0x55a6202ffad0) at ../glib/glib/gmain.c:3974
#14 0x00007f2022b9d531 in g_main_context_iterate (context=0x55a6202ffad0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at ../glib/glib/gmain.c:4047
#15 0x00007f2022b9e543 in g_main_loop_run (loop=0x55a620300f10) at ../glib/glib/gmain.c:4241
#16 0x00007f202317f0af in meta_run () at core/main.c:582
#17 0x000055a61ec8650c in main (argc=<optimized out>, argv=<optimized out>) at main.c:381
```

The error message was: "toggling down object GInotifyFileMonitor that's already queued to toggle up", what came from [here](https://github.com/linuxmint/cjs/blob/master/gi/object.cpp#L1234)

**Comment by claudiux** [comment]
@Gr3q @dragonhelios A new PR is coming soon...
