### ISSUE TITLE
weather@mockturtl Version 2.6.7 the config window wont open on Linux Mint 20

### ISSUE THREAD

**Issue by catalin560** [linuxmint/cinnamon-spices-applets#3270]
fresh install of mint, downloaded the applet and I can't set it up in any way since the configure window wont open for some reason...

**Comment by Gr3q** [comment]
An update to fix this issue was pushed earlier today, use the Spices Update
applet to update the app and let me know if it still doesn't open

Thanks

**Comment by French77** [comment]
Check the following÷ local ►share ►cinnamon ►applets ►weather@mockurtl ►3.8 ►settings-schema.json
![Update settings-schema json](https://user-images.githubusercontent.com/3099270/96351286-a0a40f80-10ba-11eb-80de-cf67840f12b6.png)

**Comment by shepherdlewis000** [comment]
Same issue here on Mint 20. No, neither manual installation with zip file nor through the Spices install applets dialog are functional.
You get an exclamation mark and greyed-out config button.

**Comment by jorgenqv** [comment]
Sometimes I needed to remove by uninstall under the Download tab in System Settings, restart and then install again. But this time the only issue when updating was a cinnamon crash on one on three LM20 installs.

**Comment by proteus8** [comment]
Just downloaded the applet. I have the same issue on Linux Mint 20 as shepherdlewis000. Can't configure and settings-schema.json has "units-page". Any suggestions?

**Comment by Gr3q** [comment]
@proteus8 if you run this in your terminal: `/usr/share/cinnamon/cinnamon-settings/xlet-settings.py "applet" "weather@mockturtl"`, does the settings open? if not, what is the error?

**Comment by proteus8** [comment]
Gr3q, the .cinnamon/configs folder was not created:

```
/usr/share/cinnamon/cinnamon-settings/xlet-settings.py "applet" "weather@mockturtl"
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/xlet-settings.py", line 579, in <module>
    window = MainWindow(xlet_type, *sys.argv[2:])
  File "/usr/share/cinnamon/cinnamon-settings/xlet-settings.py", line 146, in __init__
    self.load_instances()
  File "/usr/share/cinnamon/cinnamon-settings/xlet-settings.py", line 281, in load_instances
    dir_items = sorted(os.listdir(path))
FileNotFoundError: [Errno 2] No such file or directory: '/home/xxx/.cinnamon/configs/weather@mockturtl'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_share_cinnamon_cinnamon-settings_xlet-settings.py.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/xlet-settings.py", line 579, in <module>
    window = MainWindow(xlet_type, *sys.argv[2:])
  File "/usr/share/cinnamon/cinnamon-settings/xlet-settings.py", line 146, in __init__
    self.load_instances()
  File "/usr/share/cinnamon/cinnamon-settings/xlet-settings.py", line 281, in load_instances
    dir_items = sorted(os.listdir(path))
FileNotFoundError: [Errno 2] No such file or directory: '/home/xxx/.cinnamon/configs/weather@mockturtl'

```

**Comment by Gr3q** [comment]
@proteus8 I see, technically this is not the responsibility of the applet so the issue lies somewhere else.

Can you create the folder manually?

If so, can the configuration be opened? If not, has a .json file been created in said folfer?

**Comment by proteus8** [comment]
I created the folder, reran the command and got:

`/usr/share/cinnamon/cinnamon-settings/xlet-settings.py "applet" "weather@mockturtl"
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/xlet-settings.py", line 579, in <module>
    window = MainWindow(xlet_type, *sys.argv[2:])
  File "/usr/share/cinnamon/cinnamon-settings/xlet-settings.py", line 155, in __init__
    self.set_instance(self.instance_info[0])
IndexError: list index out of range
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_share_cinnamon_cinnamon-settings_xlet-settings.py.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/xlet-settings.py", line 579, in <module>
    window = MainWindow(xlet_type, *sys.argv[2:])
  File "/usr/share/cinnamon/cinnamon-settings/xlet-settings.py", line 155, in __init__
    self.set_instance(self.instance_info[0])
IndexError: list index out of range
`

**Comment by Gr3q** [comment]
If you create a file in the folder named `104.json` with contents it will work, because the config file is missing. Although I don't know why don't you have the correct folder+file, and I don't know can the applet modify it after. Are you using Linux Mint or something else with Cinnamon?
Contents:
```json
{
    "layout": {
        "type": "layout",
        "pages": [
            "providers",
            "presentation-section",
            "units-page",
            "info-section"
        ],
        "providers": {
            "type": "page",
            "title": "Weather",
            "sections": [
                "provider-options",
                "weather-conditions"
            ]
        },
        "presentation-section": {
            "type": "page",
            "title": "Presentation",
            "sections": [
                "panel-options",
                "presentation"
            ]
        },
        "units-page": {
            "type": "page",
            "title": "Units, Icons and Keys",
            "sections": [
                "units-section",
                "icons",
                "keybindings"
            ]
        },
        "info-section": {
            "type": "page",
            "title": "Help",
            "sections": [
                "provider-info",
                "location-info",
                "more-info",
                "submit-issue"
            ]
        },
        "provider-options": {
            "type": "section",
            "title": "Weather Provider Options",
            "keys": [
                "dataService",
                "apiKey",
                "manualLocation",
                "location",
                "saveLocation",
                "deleteLocation",
                "refreshInterval",
                "forecastDays",
                "forecastHours"
            ]
        },
        "weather-conditions": {
            "type": "section",
            "title": "Weather conditions",
            "keys": [
                "translateCondition",
                "shortConditions"
            ]
        },
        "panel-options": {
            "type": "section",
            "title": "Panel (Taskbar)",
            "keys": [
                "showTextInPanel",
                "showCommentInPanel",
                "tempTextOverride"
            ]
        },
        "presentation": {
            "type": "section",
            "title": "Popup menu",
            "keys": [
                "verticalOrientation",
                "forecastColumns",
                "forecastRows",
                "showSunrise",
                "show24Hours",
                "temperatureHighFirst",
                "tempRussianStyle",
                "locationLabelOverride"
            ]
        },
        "units-section": {
            "type": "section",
            "title": "Units",
            "keys": [
                "temperatureUnit",
                "windSpeedUnit",
                "pressureUnit",
                "distanceUnit"
            ]
        },
        "icons": {
            "type": "section",
            "title": "Icons",
            "keys": [
                "useSymbolicIcons",
                "useCustomMenuIcons",
                "useCustomAppletIcons"
            ]
        },
        "keybindings": {
            "type": "section",
            "title": "Keybindings",
            "keys": [
                "keybinding"
            ]
        },
        "provider-info": {
            "type": "section",
            "title": "How to choose a weather provider",
            "keys": [
                "provider-explanation"
            ]
        },
        "location-info": {
            "type": "section",
            "title": "Allowed location formats",
            "keys": [
                "loc-info"
            ]
        },
        "more-info": {
            "type": "section",
            "title": "View additional information",
            "keys": [
                "more-info-label",
                "getLocation"
            ]
        },
        "submit-issue": {
            "type": "section",
            "title": "Report an issue",
            "keys": [
                "issue-reporting-explanation",
                "submitIssue",
                "maintainer"
            ]
        }
    },
    "keybinding": {
        "type": "keybinding",
        "description": "Set the keybinding to call the menu",
        "default": "<Super><Shift>w",
        "value": "<Super><Shift>w"
    },
    "dataService": {
        "type": "radiogroup",
        "default": "OpenWeatherMap",
        "description": "Data service",
        "options": {
            "OpenWeatherMap": "OpenWeatherMap",
            "DarkSky (key needed)": "DarkSky",
            "MET Norway": "MetNorway",
            "Weatherbit (key needed)": "Weatherbit",
            "Yahoo": "Yahoo",
            "Climacell (key needed)": "Climacell",
            "Met Office UK (UK only)": "Met Office UK",
            "US National Weather (US only)": "US Weather"
        },
        "value": "OpenWeatherMap"
    },
    "apiKey": {
        "type": "entry",
        "default": "",
        "description": "API Key",
        "tooltip": "Copy this from your account of the used Data service and paste it here.",
        "value": ""
    },
    "manualLocation": {
        "type": "checkbox",
        "default": false,
        "description": "Manual Location",
        "tooltip": "Enable this if your location is not accurate",
        "value": false
    },
    "location": {
        "type": "entry",
        "default": "London,UK",
        "dependency": "manualLocation",
        "description": "Location",
        "tooltip": "Acceptable inputs are Latitude,Longitude. e.g.: 68.1932,17.1426 or an address.\nWaits for 3 seconds after you stop typing then refreshes the weather.",
        "value": "52.1932,0.1426"
    },
    "saveLocation": {
        "type": "button",
        "indent": true,
        "description": "Save current location to storage",
        "callback": "saveCurrentLocation",
        "dependency": "manualLocation",
        "tooltip": "Saves location information to file, so you can switch between them with buttons in the applet (what will appear if you have more than one)."
    },
    "deleteLocation": {
        "type": "button",
        "indent": true,
        "description": "Delete current location from storage",
        "callback": "deleteCurrentLocation",
        "dependency": "manualLocation",
        "tooltip": "Removes location information from storage file."
    },
    "getLocation": {
        "type": "button",
        "indent": true,
        "description": "Weather Applet at Cinnamon Spices Website",
        "callback": "locationLookup",
        "tooltip": "Opens webpage guide"
    },
    "refreshInterval": {
        "type": "spinbutton",
        "default": 15,
        "min": 5,
        "max": 360,
        "units": "minutes",
        "step": 5,
        "description": "Update interval",
        "value": 15
    },
    "forecastDays": {
        "type": "spinbutton",
        "default": 3,
        "min": 2,
        "max": 16,
        "units": "days",
        "step": 1,
        "description": "Forecast length",
        "value": 4
    },
    "forecastHours": {
        "type": "spinbutton",
        "default": 12,
        "min": 3,
        "max": 48,
        "units": "hours",
        "step": 1,
        "description": "Hourly Forecast length",
        "value": 18
    },
    "temperatureUnit": {
        "type": "radiogroup",
        "default": "celsius",
        "description": "Temperature unit",
        "options": {
            "celsius": "celsius",
            "fahrenheit": "fahrenheit"
        },
        "value": "celsius"
    },
    "windSpeedUnit": {
        "type": "combobox",
        "default": "kph",
        "description": "Wind speed unit",
        "options": {
            "kph": "kph",
            "mph": "mph",
            "m/s": "m/s",
            "knots": "Knots",
            "Beaufort": "Beaufort"
        },
        "value": "kph"
    },
    "pressureUnit": {
        "type": "combobox",
        "default": "hPa",
        "description": "Atmospheric pressure unit",
        "options": {
            "hPa": "hPa",
            "in Hg": "in Hg",
            "mm Hg": "mm Hg",
            "psi": "psi",
            "at": "at",
            "atm": "atm",
            "Pa": "Pa"
        },
        "value": "hPa"
    },
    "distanceUnit": {
        "type": "combobox",
        "default": "metric",
        "description": "Distance unit",
        "options": {
            "Metric": "metric",
            "Imperial": "imperial"
        },
        "value": "metric"
    },
    "showTextInPanel": {
        "type": "checkbox",
        "default": true,
        "description": "Display current temperature in panel",
        "value": true
    },
    "showCommentInPanel": {
        "type": "checkbox",
        "default": true,
        "description": "Show the weather condition (e.g., \"Windy\", \"Clear\") in the panel",
        "tooltip": "Only works with horizontal panels",
        "value": true
    },
    "tempTextOverride": {
        "type": "entry",
        "default": "",
        "description": "Override label on panel",
        "tooltip": "Available values are: {c} is condition, {t} is temperature and {u} is unit.\nCan be used if label does not fit on vertical panel, among other smart things.",
        "value": "{t}{u}"
    },
    "useCustomAppletIcons": {
        "type": "checkbox",
        "default": false,
        "tooltip": "Iconset is weather-icons by Erik Flowers",
        "description": "Use custom icons on the panel",
        "value": false
    },
    "verticalOrientation": {
        "type": "checkbox",
        "default": false,
        "tooltip": "Displaying forecasts from top to bottom instead from left to right.",
        "description": "Show forecast vertically",
        "value": false
    },
    "forecastColumns": {
        "type": "spinbutton",
        "default": 5,
        "min": 1,
        "max": 16,
        "units": "columns",
        "step": 1,
        "description": "Maximum number of columns for forecast",
        "value": 5
    },
    "forecastRows": {
        "type": "spinbutton",
        "default": 4,
        "min": 1,
        "max": 16,
        "units": "rows",
        "step": 1,
        "description": "Maximum number of rows for forecast",
        "value": 4
    },
    "showSunrise": {
        "type": "checkbox",
        "default": true,
        "description": "Show sunrise / sunset times",
        "value": true
    },
    "show24Hours": {
        "type": "checkbox",
        "default": false,
        "description": "Display time in 24 hour format",
        "value": false
    },
    "temperatureHighFirst": {
        "type": "checkbox",
        "default": false,
        "description": "Show high temperature first in forecast",
        "value": false
    },
    "tempRussianStyle": {
        "type": "checkbox",
        "default": false,
        "description": "Show temperature Russian style",
        "value": false
    },
    "locationLabelOverride": {
        "type": "entry",
        "default": "",
        "description": "Override location label",
        "value": ""
    },
    "translateCondition": {
        "type": "checkbox",
        "default": true,
        "description": "Translate conditions",
        "value": true
    },
    "shortConditions": {
        "type": "checkbox",
        "default": false,
        "description": "Less verbose conditions",
        "tooltip": "Currently only used with DarkSky ",
        "value": false
    },
    "useSymbolicIcons": {
        "type": "checkbox",
        "default": true,
        "tooltip": "Does not apply to custom iconset, that is symbolic by default",
        "description": "Use symbolic icons throughout the applet",
        "value": true
    },
    "useCustomMenuIcons": {
        "type": "checkbox",
        "tooltip": "Iconset is weather-icons by Erik Flowers",
        "default": false,
        "description": "Use custom icons in the popup menu",
        "value": false
    },
    "more-info-label": {
        "type": "label",
        "description": "For more information go to the Spices Website by clicking the button below. You can also comment and ask a questions to the community at this page by logging in with your Github account."
    },
    "submitIssue": {
        "type": "button",
        "indent": true,
        "description": "Submit an Issue",
        "callback": "submitIssue",
        "tooltip": "Opens webpage where you can fill out a new issue for the applet, needs a GitHub account.\n Please make sure that the issue is not already submitted."
    },
    "maintainer": {
        "type": "label",
        "description": "Current maintainer: Gr3q"
    },
    "issue-reporting-explanation": {
        "type": "label",
        "description": "If you find an issue with this applet please make a report by clicking on the button below and login in with your Github account. Don't forget to write weather@mockturtl in the top Title field to make it easier for everyone to know that the issue is about the weather applet (the form is for all Cinnamon applets)."
    },
    "provider-explanation": {
        "type": "label",
        "description": "You can use several different weather forecast providers that you choose under the first Weather Tab in this Configuration panel. Some providers require a API key to work, some have regional limits, differ in forecast length, and they all need a functional internet connection to the chosen service. The options are described in detail on the Cinnamon Spices Website, what you can access with the button further down."
    },
    "loc-info": {
        "type": "label",
        "description": "Your location in most cases work automatically but you can enter it manually by coordinates 'Latitude,Longitude' (e.g. 51.5085,-0.1257) or use 'City,Country-code' (e.g. London,UK) or try to enter {House number} {Street} {City/Town} {Postcode} {Country}. The search algorithm is very flexible with the format. After 3 seconds without typing the address you entered is replaced automatically for validating your choice."
    },
    "__md5__": "9d3a79cf785a4d458d60bcb0964c7a7b"
}
```

**Comment by proteus8** [comment]
Gr3q, I'm running Linux Mint 20. I created 104.json in the configs/weather@mockturtl folder with the contents from the previous post and got the same error as before:

`Original exception was:
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/xlet-settings.py", line 579, in <module>
    window = MainWindow(xlet_type, *sys.argv[2:])
  File "/usr/share/cinnamon/cinnamon-settings/xlet-settings.py", line 155, in __init__
    self.set_instance(self.instance_info[0])
IndexError: list index out of range`

**Comment by catalin560** [comment]
thanks! it works after updating it with the cinnamon spices update applet.
