### ISSUE TITLE
mailnagapplet@ozderya.net - Error: Mailnag daemon isn't running! is it installed?

### ISSUE THREAD

**Issue by Shaolin-Twelve** [linuxmint/cinnamon-spices-applets#4332]
As of 3 days ago, the Mailnag applet started to display two exclamation marks by the envelope emblem on the panel of my system.

On hover, the message reads "Click to see error".

On clicking the applet the message reads - "Error: Mailnag daemon isn't running! is it installed?".

Trying to start the Mailnag daemon from terminal yeilds the following output;-
---------------------------------------------------------------------------------------------------------------------------------
:~$ mailnag
INFO (2022-05-11 12:47:21): Shutting down...
Traceback (most recent call last):
  File "/usr/bin/mailnag", line 141, in <module>
    if __name__ == '__main__': main()
  File "/usr/bin/mailnag", line 127, in main
    daemon = MailnagDaemon(
  File "/usr/lib/python3/dist-packages/Mailnag/daemon/mailnagdaemon.py", line 63, in __init__
    self._memorizer.load()
  File "/usr/lib/python3/dist-packages/Mailnag/daemon/mails.py", line 270, in load
    for line in f:
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 0: invalid start byte
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 146, in apport_excepthook
    os.unlink(pr_filename)
PermissionError: [Errno 13] Permission denied: '/var/crash/_usr_bin_mailnag.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/mailnag", line 141, in <module>
    if __name__ == '__main__': main()
  File "/usr/bin/mailnag", line 127, in main
    daemon = MailnagDaemon(
  File "/usr/lib/python3/dist-packages/Mailnag/daemon/mailnagdaemon.py", line 63, in __init__
    self._memorizer.load()
  File "/usr/lib/python3/dist-packages/Mailnag/daemon/mails.py", line 270, in load
    for line in f:
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 0: invalid start byte

-----------------------------------------------------------------------------------------------------------------------
Applet Details - Mailnag (mailnagapplet@ozderya.net) -  Updated on 2021-11-07 08:34:17
----------------------------------------------------------------------------------------------------------------------

System:
Kernel: 5.4.0-110-generic x86_64 bits: 64 compiler: gcc v: 9.4.0 
Desktop: Cinnamon 4.6.7 wm: muffin dm: LightDM Distro: Linux Mint 20 Ulyana 
base: Ubuntu 20.04 focal

Graphics:
Device-1: NVIDIA TU116 [GeForce GTX 1660 Ti] driver: nvidia v: 470.103.01 
bus ID: 01:00.0 chip ID: 10de:2182 
Display: x11 server: X.Org 1.20.13 driver: nvidia resolution: 1366x768~60Hz 
OpenGL: renderer: NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2 v: 4.6.0 NVIDIA 470.103.01 
direct render: Yes 

-------------------------------------------------------------------------------------------------------------------------
Melange Log snippets -
-------------------------------------------------------------------------------------------------------------------------
info t=2022-05-10T15:08:49Z Loaded applet mailnagapplet@ozderya.net in 10 ms
error t=2022-05-10T15:08:50Z MailnagApplet ERROR: Mailnag daemon isn't running! Do you have it installed?

info t=2022-05-11T12:55:02Z Reloading applet: mailnagapplet@ozderya.net/77
info t=2022-05-11T12:55:03Z Loaded applet mailnagapplet@ozderya.net in 90 ms
error t=2022-05-11T12:55:03Z MailnagApplet ERROR: Mailnag daemon isn't running! Do you have it installed?

These errors seem to have started after a kernel upgrade and some system updates. I have had more updates and another kernel upgrade since first noticing the problem 3 days ago, none of which have sorted the mailnag daemon not loading.

**Comment by Shaolin-Twelve** [comment]
Is Mailnag maintained anymore? Seems like it has been abandoned to me - no response, no fixes - people have had this issue for a very long time. Un-&-re-install fails to fix issue. No clear instructions on how to remove fully (my accounts reappear even after purging mailnag from my system).

Sad state of afairs for an applet that is excellent when it works, much needed and useful - I have never understood why one of the most fundamental tools (email notification) to internet use, since the start of the internet, has been relegated to an app. Email is still widely used, hasn't gone away or been replaced, yet getting a simple notification that "You Have Mail" seems to be a black art these days. Some of us don't want our email clients active when there is no need to have them active - wasting resources (and electricity).

Mail notification should be part of every OS (obviously with choice to easily activate or not).

**Comment by Drugwash2** [comment]
You are commenting in the applet section, however the applet is **not** at fault for main application's error. When Mailnag is launched manually the applet does do its job - at least here in Mint 19.2.

The real problem is with the main Mailnag application which for some reason cannot launch its daemon anymore. I have just installed the current code from its GitHub **[here](https://github.com/pulb/mailnag)** and there are quite a few issues with that installation method: no plugins in the list, daemon not running, missing icon in the About dialog. However, running `mailnag &` in Terminal allows the applet to notify of new mails.

The version of Mailnag offered through Synaptic (at least in Mint 19.x) is **1.3.0** while the one at GitHub is **2.2.0**. There have been many changes between the two versions, some dependencies changed. It would be best to head there and double-check the dependencies, maybe post the bug report too if it hasn't already been posted by other user(s).
