### ISSUE TITLE
Applet Bug - Mailnage daemon isn't starting with the system boot

### ISSUE THREAD

**Issue by 666xan666** [linuxmint/cinnamon-spices-applets#6654]
### Applet version/Build date

Updated: 2024-11-29 21:51:06

### Cinnamon version

2.2.0

### Distribution

Mint 22

### Graphics hardware *and* driver used

NVIDIA Geforce RTX 4060 TI

### Applet name and maintainer

mailnagapplet@ozderya.net @hyOzd

### What happened?

Mailnag isn't starting with the system boot. Each time I need to go to menu bar =>  go to Mailnag applet => Configuration => Turn it off and on and then it is working. Of course only to time when I either reboot or lock screen/re-log. Sad.

### Other information

**journalctl -b _COMM=mailnag**
https://jumpshare.com/s/URdrVP5EtSqNHf7pUrJj

**cat ~/.config/mailnag/mailnag.cfg**
`[core]
poll_interval = 10
imap_idle_timeout = 10
mailbox_seen_flags = 1
autostart = 1
connectivity_test = networkmonitor
enabled_plugins = spamfilterplugin, libnotifyplugin

[soundplugin]
soundfile = mailnag.ogg`

**apt policy mailnag**
`mailnag:
  Zainstalowana: 2.2.0-2
  Kandydująca:   2.2.0-2
  Tabela wersji:
*** 2.2.0-2 500
        500 http://ubuntu.task.gda.pl/ubuntu noble/universe amd64 Packages
        500 http://ubuntu.task.gda.pl/ubuntu noble/universe i386 Packages
        100 /var/lib/dpkg/status`

**Comment by 666xan666** [comment]
Hi, will there be any update? :)

**Comment by makinikm** [comment]
It seems that the distributed .desktop file from the upstream mailnag package that installs it into `~/.config/autostart/mailnag.desktop` has this [setting](https://github.com/pulb/mailnag/blob/7ef91050cf3ccea2eeca13aefdbac29716806487/data/mailnag.desktop#L10):
`NoDisplay=true`
Any update to the package causes the Mailnag Startup Apps menu item to disappear from list and not start, imho.
+1 for any updates question...

**Comment by sohailb108** [comment]
For me it was the problem with `xdg` package:

```
$ mailnag
Traceback (most recent call last):
  File "/usr/bin/mailnag", line 34, in <module>
    from Mailnag.common.utils import fix_cwd
  File "/usr/lib/python3/dist-packages/Mailnag/common/utils.py", line 20, in <module>
    import xdg.BaseDirectory as base
ModuleNotFoundError: No module named 'xdg.BaseDirectory'
```

A normal install or re-install of the package didn't help. It was a problem with my local cache, removing it solved the problem:
```bash
rm -rf ~/.local/lib/python3.*/site-packages/xdg
sudo apt install --reinstall python3-xdg
```
